### ISSUE TITLE
java.io.IOException: Cannot run program "karma": error=2, No such file or directory

### ISSUE THREAD

**Issue by javazquez** [lispcast/clojurescript-test#1]
Hello, 
I followed the instructions given and I am running into the following error. The directories referenced in the error do exist. Any guidance would be greatly appreciated.

java.io.IOException: Cannot run program "karma": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at doo.shell$exec_BANG_.invokeStatic(shell.clj:50)
	at doo.shell$exec_BANG_.invoke(shell.clj:43)
	at doo.core$install_BANG_.invokeStatic(core.clj:177)
	at doo.core$install_BANG_.invoke(core.clj:170)
	at user$eval7221$fn__7226.invoke(form-init2801645405632949850.clj:1)
	at cljs.closure$watch$buildf__6959.invoke(closure.clj:2662)
	at cljs.closure$watch.invokeStatic(closure.clj:2689)
	at cljs.closure$watch.invoke(closure.clj:2633)
	at cljs.build.api$watch.invokeStatic(api.clj:219)
	at cljs.build.api$watch.invoke(api.clj:207)
	at cljs.build.api$watch.invokeStatic(api.clj:216)
	at cljs.build.api$watch.invoke(api.clj:207)
	at cljs.build.api$watch.invokeStatic(api.clj:210)
	at cljs.build.api$watch.invoke(api.clj:207)
	at user$eval7221.invokeStatic(form-init2801645405632949850.clj:1)
	at user$eval7221.invoke(form-init2801645405632949850.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.foWatching paths: /Users/username/code/cljs/clojurescript-test/cljs-src, /Users/username/code/cljs/clojurescript-test/cljs-test
rkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 35 more

Thanks!
-Juan

**Comment by javazquez** [comment]
looks like adding the following fix the issue
npm install -g karma-cli

Thanks,
Juan
